[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]
formatter = { command = "prettierd", args = ["--stdin-filepath", "file.ts"] }

[[language]]
name = "html"
language-servers = ["vscode-html-language-server"]
formatter = { command = "prettierd", args = ["--stdin-filepath", "file.html"] }

[[language]]
name = "css"
language-servers = ["vscode-css-language-server"]
formatter = { command = "prettierd", args = ["--stdin-filepath", "file.css"] }

