[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]

[[language]]
name = "typescript"
language-servers = ["typescript-language-server", "tailwindcss-ls"]
formatter = { command = "prettierd", args = ["--stdin-filepath", "file.ts"] }

[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "tailwindcss-ls"]
formatter = { command = "prettierd", args = ["--stdin-filepath", "file.html"] }

[[language]]
name = "css"
language-servers = ["vscode-css-language-server", "tailwindcss-ls"]
formatter = { command = "prettierd", args = ["--stdin-filepath", "file.css"] }

